pub use crate::sys::curandStatus_t as CudaTargetStatus;
#[allow(unused_imports)]
use crate::sys::*;
use cuda_libs_cudart::sys::*;
pub struct CurandGenerator {
    pub(crate) handle: crate::sys::curandGenerator_t,
}
impl CurandGenerator {
    #[doc = " \\brief Set the current stream for CURAND kernel launches.\n\n Set the current stream for CURAND kernel launches.  All library functions\n will use this stream until set again.\n\n \\param generator - Generator to modify\n \\param stream - Stream to use or ::NULL for null stream\n\n \\return\n - CURAND_STATUS_NOT_INITIALIZED if the generator was never created \\n\n - CURAND_STATUS_SUCCESS if stream was set successfully \\n"]
    pub unsafe fn curandSetStream(
        &self,
        stream: cudaStream_t,
    ) -> Result<(), crate::sys::curandStatus_t> {
        let status = unsafe { crate::sys::curandSetStream(self.handle, stream) };
        if status == crate::sys::curandStatus_t::CURAND_STATUS_SUCCESS {
            Ok(())
        } else {
            Err(status)
        }
    }
    #[doc = " \\brief Set the seed value of the pseudo-random number generator.\n\n Set the seed value of the pseudorandom number generator.\n All values of seed are valid.  Different seeds will produce different sequences.\n Different seeds will often not be statistically correlated with each other,\n but some pairs of seed values may generate sequences which are statistically correlated.\n\n \\param generator - Generator to modify\n \\param seed - Seed value\n\n \\return\n - CURAND_STATUS_NOT_INITIALIZED if the generator was never created \\n\n - CURAND_STATUS_TYPE_ERROR if the generator is not a pseudorandom number generator \\n\n - CURAND_STATUS_SUCCESS if generator seed was set successfully \\n"]
    pub unsafe fn curandSetPseudoRandomGeneratorSeed(
        &self,
        seed: ::std::os::raw::c_ulonglong,
    ) -> Result<(), crate::sys::curandStatus_t> {
        let status = unsafe { crate::sys::curandSetPseudoRandomGeneratorSeed(self.handle, seed) };
        if status == crate::sys::curandStatus_t::CURAND_STATUS_SUCCESS {
            Ok(())
        } else {
            Err(status)
        }
    }
    #[doc = " \\brief Set the absolute offset of the pseudo or quasirandom number generator.\n\n Set the absolute offset of the pseudo or quasirandom number generator.\n\n All values of offset are valid.  The offset position is absolute, not\n relative to the current position in the sequence.\n\n \\param generator - Generator to modify\n \\param offset - Absolute offset position\n\n \\return\n - CURAND_STATUS_NOT_INITIALIZED if the generator was never created \\n\n - CURAND_STATUS_SUCCESS if generator offset was set successfully \\n"]
    pub unsafe fn curandSetGeneratorOffset(
        &self,
        offset: ::std::os::raw::c_ulonglong,
    ) -> Result<(), crate::sys::curandStatus_t> {
        let status = unsafe { crate::sys::curandSetGeneratorOffset(self.handle, offset) };
        if status == crate::sys::curandStatus_t::CURAND_STATUS_SUCCESS {
            Ok(())
        } else {
            Err(status)
        }
    }
    #[doc = " \\brief Set the ordering of results of the pseudo or quasirandom number generator.\n\n Set the ordering of results of the pseudo or quasirandom number generator.\n\n Legal values of \\p order for pseudorandom generators are:\n - CURAND_ORDERING_PSEUDO_DEFAULT\n - CURAND_ORDERING_PSEUDO_BEST\n - CURAND_ORDERING_PSEUDO_SEEDED\n - CURAND_ORDERING_PSEUDO_LEGACY\n\n Legal values of \\p order for quasirandom generators are:\n - CURAND_ORDERING_QUASI_DEFAULT\n\n \\param generator - Generator to modify\n \\param order - Ordering of results\n\n \\return\n - CURAND_STATUS_NOT_INITIALIZED if the generator was never created \\n\n - CURAND_STATUS_OUT_OF_RANGE if the ordering is not valid \\n\n - CURAND_STATUS_SUCCESS if generator ordering was set successfully \\n"]
    pub unsafe fn curandSetGeneratorOrdering(
        &self,
        order: curandOrdering_t,
    ) -> Result<(), crate::sys::curandStatus_t> {
        let status = unsafe { crate::sys::curandSetGeneratorOrdering(self.handle, order) };
        if status == crate::sys::curandStatus_t::CURAND_STATUS_SUCCESS {
            Ok(())
        } else {
            Err(status)
        }
    }
    #[doc = " \\brief Set the number of dimensions.\n\n Set the number of dimensions to be generated by the quasirandom number\n generator.\n\n Legal values for \\p num_dimensions are 1 to 20000.\n\n \\param generator - Generator to modify\n \\param num_dimensions - Number of dimensions\n\n \\return\n - CURAND_STATUS_NOT_INITIALIZED if the generator was never created \\n\n - CURAND_STATUS_OUT_OF_RANGE if num_dimensions is not valid \\n\n - CURAND_STATUS_TYPE_ERROR if the generator is not a quasirandom number generator \\n\n - CURAND_STATUS_SUCCESS if generator ordering was set successfully \\n"]
    pub unsafe fn curandSetQuasiRandomGeneratorDimensions(
        &self,
        num_dimensions: ::std::os::raw::c_uint,
    ) -> Result<(), crate::sys::curandStatus_t> {
        let status = unsafe {
            crate::sys::curandSetQuasiRandomGeneratorDimensions(self.handle, num_dimensions)
        };
        if status == crate::sys::curandStatus_t::CURAND_STATUS_SUCCESS {
            Ok(())
        } else {
            Err(status)
        }
    }
    #[doc = " \\brief Generate 32-bit pseudo or quasirandom numbers.\n\n Use \\p generator to generate \\p num 32-bit results into the device memory at\n \\p outputPtr.  The device memory must have been previously allocated and be\n large enough to hold all the results.  Launches are done with the stream\n set using ::curandSetStream(), or the null stream if no stream has been set.\n\n Results are 32-bit values with every bit random.\n\n \\param generator - Generator to use\n \\param outputPtr - Pointer to device memory to store CUDA-generated results, or\n                 Pointer to host memory to store CPU-generated results\n \\param num - Number of random 32-bit values to generate\n\n \\return\n - CURAND_STATUS_ALLOCATION_FAILED if memory could not be allocated \\n\n - CURAND_STATUS_NOT_INITIALIZED if the generator was never created \\n\n - CURAND_STATUS_PREEXISTING_FAILURE if there was an existing error from\n     a previous kernel launch \\n\n - CURAND_STATUS_LENGTH_NOT_MULTIPLE if the number of output samples is\n    not a multiple of the quasirandom dimension \\n\n - CURAND_STATUS_LAUNCH_FAILURE if the kernel launch failed for any reason \\n\n - CURAND_STATUS_TYPE_ERROR if the generator is a 64 bit quasirandom generator.\n (use ::curandGenerateLongLong() with 64 bit quasirandom generators)\n - CURAND_STATUS_SUCCESS if the results were generated successfully \\n"]
    pub unsafe fn curandGenerate<T: ::cuda_libs::types::CudaAsPtr>(
        &self,
        mut outputPtr: T,
        num: usize,
    ) -> Result<(), crate::sys::curandStatus_t> {
        let status = unsafe {
            crate::sys::curandGenerate(
                self.handle,
                outputPtr.as_mut_ptr() as *mut ::std::os::raw::c_uint,
                num,
            )
        };
        if status == crate::sys::curandStatus_t::CURAND_STATUS_SUCCESS {
            Ok(())
        } else {
            Err(status)
        }
    }
    #[doc = " \\brief Generate 64-bit quasirandom numbers.\n\n Use \\p generator to generate \\p num 64-bit results into the device memory at\n \\p outputPtr.  The device memory must have been previously allocated and be\n large enough to hold all the results.  Launches are done with the stream\n set using ::curandSetStream(), or the null stream if no stream has been set.\n\n Results are 64-bit values with every bit random.\n\n \\param generator - Generator to use\n \\param outputPtr - Pointer to device memory to store CUDA-generated results, or\n                 Pointer to host memory to store CPU-generated results\n \\param num - Number of random 64-bit values to generate\n\n \\return\n - CURAND_STATUS_NOT_INITIALIZED if the generator was never created \\n\n - CURAND_STATUS_PREEXISTING_FAILURE if there was an existing error from\n     a previous kernel launch \\n\n - CURAND_STATUS_LENGTH_NOT_MULTIPLE if the number of output samples is\n    not a multiple of the quasirandom dimension \\n\n - CURAND_STATUS_LAUNCH_FAILURE if the kernel launch failed for any reason \\n\n - CURAND_STATUS_TYPE_ERROR if the generator is not a 64 bit quasirandom generator\\n\n - CURAND_STATUS_SUCCESS if the results were generated successfully \\n"]
    pub unsafe fn curandGenerateLongLong<T: ::cuda_libs::types::CudaAsPtr>(
        &self,
        mut outputPtr: T,
        num: usize,
    ) -> Result<(), crate::sys::curandStatus_t> {
        let status = unsafe {
            crate::sys::curandGenerateLongLong(
                self.handle,
                outputPtr.as_mut_ptr() as *mut ::std::os::raw::c_ulonglong,
                num,
            )
        };
        if status == crate::sys::curandStatus_t::CURAND_STATUS_SUCCESS {
            Ok(())
        } else {
            Err(status)
        }
    }
    #[doc = " \\brief Generate uniformly distributed floats.\n\n Use \\p generator to generate \\p num float results into the device memory at\n \\p outputPtr.  The device memory must have been previously allocated and be\n large enough to hold all the results.  Launches are done with the stream\n set using ::curandSetStream(), or the null stream if no stream has been set.\n\n Results are 32-bit floating point values between \\p 0.0f and \\p 1.0f,\n excluding \\p 0.0f and including \\p 1.0f.\n\n \\param generator - Generator to use\n \\param outputPtr - Pointer to device memory to store CUDA-generated results, or\n                 Pointer to host memory to store CPU-generated results\n \\param num - Number of floats to generate\n\n \\return\n - CURAND_STATUS_ALLOCATION_FAILED if memory could not be allocated \\n\n - CURAND_STATUS_NOT_INITIALIZED if the generator was never created \\n\n - CURAND_STATUS_PREEXISTING_FAILURE if there was an existing error from\n    a previous kernel launch \\n\n - CURAND_STATUS_LAUNCH_FAILURE if the kernel launch failed for any reason \\n\n - CURAND_STATUS_LENGTH_NOT_MULTIPLE if the number of output samples is\n    not a multiple of the quasirandom dimension \\n\n - CURAND_STATUS_SUCCESS if the results were generated successfully \\n"]
    pub unsafe fn curandGenerateUniform<T: ::cuda_libs::types::CudaAsPtr>(
        &self,
        mut outputPtr: T,
        num: usize,
    ) -> Result<(), crate::sys::curandStatus_t> {
        let status = unsafe {
            crate::sys::curandGenerateUniform(self.handle, outputPtr.as_mut_ptr() as *mut f32, num)
        };
        if status == crate::sys::curandStatus_t::CURAND_STATUS_SUCCESS {
            Ok(())
        } else {
            Err(status)
        }
    }
    #[doc = " \\brief Generate uniformly distributed doubles.\n\n Use \\p generator to generate \\p num double results into the device memory at\n \\p outputPtr.  The device memory must have been previously allocated and be\n large enough to hold all the results.  Launches are done with the stream\n set using ::curandSetStream(), or the null stream if no stream has been set.\n\n Results are 64-bit double precision floating point values between\n \\p 0.0 and \\p 1.0, excluding \\p 0.0 and including \\p 1.0.\n\n \\param generator - Generator to use\n \\param outputPtr - Pointer to device memory to store CUDA-generated results, or\n                 Pointer to host memory to store CPU-generated results\n \\param num - Number of doubles to generate\n\n \\return\n - CURAND_STATUS_ALLOCATION_FAILED if memory could not be allocated \\n\n - CURAND_STATUS_NOT_INITIALIZED if the generator was never created \\n\n - CURAND_STATUS_PREEXISTING_FAILURE if there was an existing error from\n    a previous kernel launch \\n\n - CURAND_STATUS_LAUNCH_FAILURE if the kernel launch failed for any reason \\n\n - CURAND_STATUS_LENGTH_NOT_MULTIPLE if the number of output samples is\n    not a multiple of the quasirandom dimension \\n\n - CURAND_STATUS_DOUBLE_PRECISION_REQUIRED if the GPU does not support double precision \\n\n - CURAND_STATUS_SUCCESS if the results were generated successfully \\n"]
    pub unsafe fn curandGenerateUniformDouble<T: ::cuda_libs::types::CudaAsPtr>(
        &self,
        mut outputPtr: T,
        num: usize,
    ) -> Result<(), crate::sys::curandStatus_t> {
        let status = unsafe {
            crate::sys::curandGenerateUniformDouble(
                self.handle,
                outputPtr.as_mut_ptr() as *mut f64,
                num,
            )
        };
        if status == crate::sys::curandStatus_t::CURAND_STATUS_SUCCESS {
            Ok(())
        } else {
            Err(status)
        }
    }
    #[doc = " \\brief Generate normally distributed doubles.\n\n Use \\p generator to generate \\p n float results into the device memory at\n \\p outputPtr.  The device memory must have been previously allocated and be\n large enough to hold all the results.  Launches are done with the stream\n set using ::curandSetStream(), or the null stream if no stream has been set.\n\n Results are 32-bit floating point values with mean \\p mean and standard\n deviation \\p stddev.\n\n Normally distributed results are generated from pseudorandom generators\n with a Box-Muller transform, and so require \\p n to be even.\n Quasirandom generators use an inverse cumulative distribution\n function to preserve dimensionality.\n\n There may be slight numerical differences between results generated\n on the GPU with generators created with ::curandCreateGenerator()\n and results calculated on the CPU with generators created with\n ::curandCreateGeneratorHost().  These differences arise because of\n differences in results for transcendental functions.  In addition,\n future versions of CURAND may use newer versions of the CUDA math\n library, so different versions of CURAND may give slightly different\n numerical values.\n\n \\param generator - Generator to use\n \\param outputPtr - Pointer to device memory to store CUDA-generated results, or\n                 Pointer to host memory to store CPU-generated results\n \\param n - Number of floats to generate\n \\param mean - Mean of normal distribution\n \\param stddev - Standard deviation of normal distribution\n\n \\return\n - CURAND_STATUS_ALLOCATION_FAILED if memory could not be allocated \\n\n - CURAND_STATUS_NOT_INITIALIZED if the generator was never created \\n\n - CURAND_STATUS_PREEXISTING_FAILURE if there was an existing error from\n    a previous kernel launch \\n\n - CURAND_STATUS_LAUNCH_FAILURE if the kernel launch failed for any reason \\n\n - CURAND_STATUS_LENGTH_NOT_MULTIPLE if the number of output samples is\n    not a multiple of the quasirandom dimension, or is not a multiple\n    of two for pseudorandom generators \\n\n - CURAND_STATUS_SUCCESS if the results were generated successfully \\n"]
    pub unsafe fn curandGenerateNormal<T: ::cuda_libs::types::CudaAsPtr>(
        &self,
        mut outputPtr: T,
        n: usize,
        mean: f32,
        stddev: f32,
    ) -> Result<(), crate::sys::curandStatus_t> {
        let status = unsafe {
            crate::sys::curandGenerateNormal(
                self.handle,
                outputPtr.as_mut_ptr() as *mut f32,
                n,
                mean,
                stddev,
            )
        };
        if status == crate::sys::curandStatus_t::CURAND_STATUS_SUCCESS {
            Ok(())
        } else {
            Err(status)
        }
    }
    #[doc = " \\brief Generate normally distributed doubles.\n\n Use \\p generator to generate \\p n double results into the device memory at\n \\p outputPtr.  The device memory must have been previously allocated and be\n large enough to hold all the results.  Launches are done with the stream\n set using ::curandSetStream(), or the null stream if no stream has been set.\n\n Results are 64-bit floating point values with mean \\p mean and standard\n deviation \\p stddev.\n\n Normally distributed results are generated from pseudorandom generators\n with a Box-Muller transform, and so require \\p n to be even.\n Quasirandom generators use an inverse cumulative distribution\n function to preserve dimensionality.\n\n There may be slight numerical differences between results generated\n on the GPU with generators created with ::curandCreateGenerator()\n and results calculated on the CPU with generators created with\n ::curandCreateGeneratorHost().  These differences arise because of\n differences in results for transcendental functions.  In addition,\n future versions of CURAND may use newer versions of the CUDA math\n library, so different versions of CURAND may give slightly different\n numerical values.\n\n \\param generator - Generator to use\n \\param outputPtr - Pointer to device memory to store CUDA-generated results, or\n                 Pointer to host memory to store CPU-generated results\n \\param n - Number of doubles to generate\n \\param mean - Mean of normal distribution\n \\param stddev - Standard deviation of normal distribution\n\n \\return\n - CURAND_STATUS_ALLOCATION_FAILED if memory could not be allocated \\n\n - CURAND_STATUS_NOT_INITIALIZED if the generator was never created \\n\n - CURAND_STATUS_PREEXISTING_FAILURE if there was an existing error from\n    a previous kernel launch \\n\n - CURAND_STATUS_LAUNCH_FAILURE if the kernel launch failed for any reason \\n\n - CURAND_STATUS_LENGTH_NOT_MULTIPLE if the number of output samples is\n    not a multiple of the quasirandom dimension, or is not a multiple\n    of two for pseudorandom generators \\n\n - CURAND_STATUS_DOUBLE_PRECISION_REQUIRED if the GPU does not support double precision \\n\n - CURAND_STATUS_SUCCESS if the results were generated successfully \\n"]
    pub unsafe fn curandGenerateNormalDouble<T: ::cuda_libs::types::CudaAsPtr>(
        &self,
        mut outputPtr: T,
        n: usize,
        mean: f64,
        stddev: f64,
    ) -> Result<(), crate::sys::curandStatus_t> {
        let status = unsafe {
            crate::sys::curandGenerateNormalDouble(
                self.handle,
                outputPtr.as_mut_ptr() as *mut f64,
                n,
                mean,
                stddev,
            )
        };
        if status == crate::sys::curandStatus_t::CURAND_STATUS_SUCCESS {
            Ok(())
        } else {
            Err(status)
        }
    }
    #[doc = " \\brief Generate log-normally distributed floats.\n\n Use \\p generator to generate \\p n float results into the device memory at\n \\p outputPtr.  The device memory must have been previously allocated and be\n large enough to hold all the results.  Launches are done with the stream\n set using ::curandSetStream(), or the null stream if no stream has been set.\n\n Results are 32-bit floating point values with log-normal distribution based on\n an associated normal distribution with mean \\p mean and standard deviation \\p stddev.\n\n Normally distributed results are generated from pseudorandom generators\n with a Box-Muller transform, and so require \\p n to be even.\n Quasirandom generators use an inverse cumulative distribution\n function to preserve dimensionality.\n The normally distributed results are transformed into log-normal distribution.\n\n There may be slight numerical differences between results generated\n on the GPU with generators created with ::curandCreateGenerator()\n and results calculated on the CPU with generators created with\n ::curandCreateGeneratorHost().  These differences arise because of\n differences in results for transcendental functions.  In addition,\n future versions of CURAND may use newer versions of the CUDA math\n library, so different versions of CURAND may give slightly different\n numerical values.\n\n \\param generator - Generator to use\n \\param outputPtr - Pointer to device memory to store CUDA-generated results, or\n                 Pointer to host memory to store CPU-generated results\n \\param n - Number of floats to generate\n \\param mean - Mean of associated normal distribution\n \\param stddev - Standard deviation of associated normal distribution\n\n \\return\n - CURAND_STATUS_ALLOCATION_FAILED if memory could not be allocated \\n\n - CURAND_STATUS_NOT_INITIALIZED if the generator was never created \\n\n - CURAND_STATUS_PREEXISTING_FAILURE if there was an existing error from\n    a previous kernel launch \\n\n - CURAND_STATUS_LAUNCH_FAILURE if the kernel launch failed for any reason \\n\n - CURAND_STATUS_LENGTH_NOT_MULTIPLE if the number of output samples is\n    not a multiple of the quasirandom dimension, or is not a multiple\n    of two for pseudorandom generators \\n\n - CURAND_STATUS_SUCCESS if the results were generated successfully \\n"]
    pub unsafe fn curandGenerateLogNormal<T: ::cuda_libs::types::CudaAsPtr>(
        &self,
        mut outputPtr: T,
        n: usize,
        mean: f32,
        stddev: f32,
    ) -> Result<(), crate::sys::curandStatus_t> {
        let status = unsafe {
            crate::sys::curandGenerateLogNormal(
                self.handle,
                outputPtr.as_mut_ptr() as *mut f32,
                n,
                mean,
                stddev,
            )
        };
        if status == crate::sys::curandStatus_t::CURAND_STATUS_SUCCESS {
            Ok(())
        } else {
            Err(status)
        }
    }
    #[doc = " \\brief Generate log-normally distributed doubles.\n\n Use \\p generator to generate \\p n double results into the device memory at\n \\p outputPtr.  The device memory must have been previously allocated and be\n large enough to hold all the results.  Launches are done with the stream\n set using ::curandSetStream(), or the null stream if no stream has been set.\n\n Results are 64-bit floating point values with log-normal distribution based on\n an associated normal distribution with mean \\p mean and standard deviation \\p stddev.\n\n Normally distributed results are generated from pseudorandom generators\n with a Box-Muller transform, and so require \\p n to be even.\n Quasirandom generators use an inverse cumulative distribution\n function to preserve dimensionality.\n The normally distributed results are transformed into log-normal distribution.\n\n There may be slight numerical differences between results generated\n on the GPU with generators created with ::curandCreateGenerator()\n and results calculated on the CPU with generators created with\n ::curandCreateGeneratorHost().  These differences arise because of\n differences in results for transcendental functions.  In addition,\n future versions of CURAND may use newer versions of the CUDA math\n library, so different versions of CURAND may give slightly different\n numerical values.\n\n \\param generator - Generator to use\n \\param outputPtr - Pointer to device memory to store CUDA-generated results, or\n                 Pointer to host memory to store CPU-generated results\n \\param n - Number of doubles to generate\n \\param mean - Mean of normal distribution\n \\param stddev - Standard deviation of normal distribution\n\n \\return\n - CURAND_STATUS_ALLOCATION_FAILED if memory could not be allocated \\n\n - CURAND_STATUS_NOT_INITIALIZED if the generator was never created \\n\n - CURAND_STATUS_PREEXISTING_FAILURE if there was an existing error from\n    a previous kernel launch \\n\n - CURAND_STATUS_LAUNCH_FAILURE if the kernel launch failed for any reason \\n\n - CURAND_STATUS_LENGTH_NOT_MULTIPLE if the number of output samples is\n    not a multiple of the quasirandom dimension, or is not a multiple\n    of two for pseudorandom generators \\n\n - CURAND_STATUS_DOUBLE_PRECISION_REQUIRED if the GPU does not support double precision \\n\n - CURAND_STATUS_SUCCESS if the results were generated successfully \\n"]
    pub unsafe fn curandGenerateLogNormalDouble<T: ::cuda_libs::types::CudaAsPtr>(
        &self,
        mut outputPtr: T,
        n: usize,
        mean: f64,
        stddev: f64,
    ) -> Result<(), crate::sys::curandStatus_t> {
        let status = unsafe {
            crate::sys::curandGenerateLogNormalDouble(
                self.handle,
                outputPtr.as_mut_ptr() as *mut f64,
                n,
                mean,
                stddev,
            )
        };
        if status == crate::sys::curandStatus_t::CURAND_STATUS_SUCCESS {
            Ok(())
        } else {
            Err(status)
        }
    }
    #[doc = " \\brief Generate Poisson-distributed unsigned ints.\n\n Use \\p generator to generate \\p n unsigned int results into device memory at\n \\p outputPtr.  The device memory must have been previously allocated and must be\n large enough to hold all the results.  Launches are done with the stream\n set using ::curandSetStream(), or the null stream if no stream has been set.\n\n Results are 32-bit unsigned int point values with Poisson distribution, with lambda \\p lambda.\n\n \\param generator - Generator to use\n \\param outputPtr - Pointer to device memory to store CUDA-generated results, or\n                 Pointer to host memory to store CPU-generated results\n \\param n - Number of unsigned ints to generate\n \\param lambda - lambda for the Poisson distribution\n\n \\return\n - CURAND_STATUS_ALLOCATION_FAILED if memory could not be allocated \\n\n - CURAND_STATUS_NOT_INITIALIZED if the generator was never created \\n\n - CURAND_STATUS_PREEXISTING_FAILURE if there was an existing error from\n    a previous kernel launch \\n\n - CURAND_STATUS_LAUNCH_FAILURE if the kernel launch failed for any reason \\n\n - CURAND_STATUS_LENGTH_NOT_MULTIPLE if the number of output samples is\n    not a multiple of the quasirandom dimension\\n\n - CURAND_STATUS_DOUBLE_PRECISION_REQUIRED if the GPU or sm does not support double precision \\n\n - CURAND_STATUS_OUT_OF_RANGE if lambda is non-positive or greater than 400,000 \\n\n - CURAND_STATUS_SUCCESS if the results were generated successfully \\n"]
    pub unsafe fn curandGeneratePoisson<T: ::cuda_libs::types::CudaAsPtr>(
        &self,
        mut outputPtr: T,
        n: usize,
        lambda: f64,
    ) -> Result<(), crate::sys::curandStatus_t> {
        let status = unsafe {
            crate::sys::curandGeneratePoisson(
                self.handle,
                outputPtr.as_mut_ptr() as *mut ::std::os::raw::c_uint,
                n,
                lambda,
            )
        };
        if status == crate::sys::curandStatus_t::CURAND_STATUS_SUCCESS {
            Ok(())
        } else {
            Err(status)
        }
    }
    pub unsafe fn curandGeneratePoissonMethod<T: ::cuda_libs::types::CudaAsPtr>(
        &self,
        mut outputPtr: T,
        n: usize,
        lambda: f64,
        method: curandMethod_t,
    ) -> Result<(), crate::sys::curandStatus_t> {
        let status = unsafe {
            crate::sys::curandGeneratePoissonMethod(
                self.handle,
                outputPtr.as_mut_ptr() as *mut ::std::os::raw::c_uint,
                n,
                lambda,
                method,
            )
        };
        if status == crate::sys::curandStatus_t::CURAND_STATUS_SUCCESS {
            Ok(())
        } else {
            Err(status)
        }
    }
    pub unsafe fn curandGenerateBinomial<T: ::cuda_libs::types::CudaAsPtr>(
        &self,
        mut outputPtr: T,
        num: usize,
        n: ::std::os::raw::c_uint,
        p: f64,
    ) -> Result<(), crate::sys::curandStatus_t> {
        let status = unsafe {
            crate::sys::curandGenerateBinomial(
                self.handle,
                outputPtr.as_mut_ptr() as *mut ::std::os::raw::c_uint,
                num,
                n,
                p,
            )
        };
        if status == crate::sys::curandStatus_t::CURAND_STATUS_SUCCESS {
            Ok(())
        } else {
            Err(status)
        }
    }
    pub unsafe fn curandGenerateBinomialMethod<T: ::cuda_libs::types::CudaAsPtr>(
        &self,
        mut outputPtr: T,
        num: usize,
        n: ::std::os::raw::c_uint,
        p: f64,
        method: curandMethod_t,
    ) -> Result<(), crate::sys::curandStatus_t> {
        let status = unsafe {
            crate::sys::curandGenerateBinomialMethod(
                self.handle,
                outputPtr.as_mut_ptr() as *mut ::std::os::raw::c_uint,
                num,
                n,
                p,
                method,
            )
        };
        if status == crate::sys::curandStatus_t::CURAND_STATUS_SUCCESS {
            Ok(())
        } else {
            Err(status)
        }
    }
    #[doc = " \\brief Setup starting states.\n\n Generate the starting state of the generator.  This function is\n automatically called by generation functions such as\n ::curandGenerate() and ::curandGenerateUniform().\n It can be called manually for performance testing reasons to separate\n timings for starting state generation and random number generation.\n\n \\param generator - Generator to update\n\n \\return\n - CURAND_STATUS_ALLOCATION_FAILED if memory could not be allocated \\n\n - CURAND_STATUS_NOT_INITIALIZED if the generator was never created \\n\n - CURAND_STATUS_PREEXISTING_FAILURE if there was an existing error from\n     a previous kernel launch \\n\n - CURAND_STATUS_LAUNCH_FAILURE if the kernel launch failed for any reason \\n\n - CURAND_STATUS_SUCCESS if the seeds were generated successfully \\n"]
    pub unsafe fn curandGenerateSeeds(&self) -> Result<(), crate::sys::curandStatus_t> {
        let status = unsafe { crate::sys::curandGenerateSeeds(self.handle) };
        if status == crate::sys::curandStatus_t::CURAND_STATUS_SUCCESS {
            Ok(())
        } else {
            Err(status)
        }
    }
}
#[doc = " \\brief Return the version number of the library.\n\n Return in \\p *version the version number of the dynamically linked CURAND\n library.  The format is the same as CUDART_VERSION from the CUDA Runtime.\n The only supported configuration is CURAND version equal to CUDA Runtime\n version.\n\n \\param version - CURAND library version\n\n \\return\n - CURAND_STATUS_SUCCESS if the version number was successfully returned \\n"]
pub unsafe fn curandGetVersion() -> Result<::std::os::raw::c_int, crate::sys::curandStatus_t> {
    let mut out_0: std::mem::MaybeUninit<::std::os::raw::c_int> = std::mem::MaybeUninit::uninit();
    let status = unsafe { crate::sys::curandGetVersion(out_0.as_mut_ptr() as *mut _) };
    if status == crate::sys::curandStatus_t::CURAND_STATUS_SUCCESS {
        unsafe { Ok(out_0.assume_init()) }
    } else {
        Err(status)
    }
}
#[doc = " \\brief Return the value of the curand property.\n\n Return in \\p *value the number for the property described by \\p type of the\n dynamically linked CURAND library.\n\n \\param type - CUDA library property\n \\param value - integer value for the requested property\n\n \\return\n - CURAND_STATUS_SUCCESS if the property value was successfully returned \\n\n - CURAND_STATUS_OUT_OF_RANGE if the property type is not recognized \\n"]
pub unsafe fn curandGetProperty(
    type_: libraryPropertyType,
) -> Result<::std::os::raw::c_int, crate::sys::curandStatus_t> {
    let mut out_1: std::mem::MaybeUninit<::std::os::raw::c_int> = std::mem::MaybeUninit::uninit();
    let status = unsafe { crate::sys::curandGetProperty(type_, out_1.as_mut_ptr() as *mut _) };
    if status == crate::sys::curandStatus_t::CURAND_STATUS_SUCCESS {
        unsafe { Ok(out_1.assume_init()) }
    } else {
        Err(status)
    }
}
#[doc = " \\brief Get direction vectors for 32-bit quasirandom number generation.\n\n Get a pointer to an array of direction vectors that can be used\n for quasirandom number generation.  The resulting pointer will\n reference an array of direction vectors in host memory.\n\n The array contains vectors for many dimensions.  Each dimension\n has 32 vectors.  Each individual vector is an unsigned int.\n\n Legal values for \\p set are:\n - CURAND_DIRECTION_VECTORS_32_JOEKUO6 (20,000 dimensions)\n - CURAND_SCRAMBLED_DIRECTION_VECTORS_32_JOEKUO6 (20,000 dimensions)\n\n \\param vectors - Address of pointer in which to return direction vectors\n \\param set - Which set of direction vectors to use\n\n \\return\n - CURAND_STATUS_OUT_OF_RANGE if the choice of set is invalid \\n\n - CURAND_STATUS_SUCCESS if the pointer was set successfully \\n"]
pub unsafe fn curandGetDirectionVectors32<T: ::cuda_libs::types::CudaAsPtr>(
    mut vectors: T,
    set: curandDirectionVectorSet_t,
) -> Result<(), crate::sys::curandStatus_t> {
    let status = unsafe {
        crate::sys::curandGetDirectionVectors32(
            vectors.as_mut_ptr() as *mut *mut curandDirectionVectors32_t,
            set,
        )
    };
    if status == crate::sys::curandStatus_t::CURAND_STATUS_SUCCESS {
        Ok(())
    } else {
        Err(status)
    }
}
#[doc = " \\brief Get scramble constants for 32-bit scrambled Sobol' .\n\n Get a pointer to an array of scramble constants that can be used\n for quasirandom number generation.  The resulting pointer will\n reference an array of unsinged ints in host memory.\n\n The array contains constants for many dimensions.  Each dimension\n has a single unsigned int constant.\n\n \\param constants - Address of pointer in which to return scramble constants\n\n \\return\n - CURAND_STATUS_SUCCESS if the pointer was set successfully \\n"]
pub unsafe fn curandGetScrambleConstants32(
) -> Result<*mut ::std::os::raw::c_uint, crate::sys::curandStatus_t> {
    let mut out_0: std::mem::MaybeUninit<*mut ::std::os::raw::c_uint> =
        std::mem::MaybeUninit::uninit();
    let status = unsafe { crate::sys::curandGetScrambleConstants32(out_0.as_mut_ptr() as *mut _) };
    if status == crate::sys::curandStatus_t::CURAND_STATUS_SUCCESS {
        unsafe { Ok(out_0.assume_init()) }
    } else {
        Err(status)
    }
}
#[doc = " \\brief Get direction vectors for 64-bit quasirandom number generation.\n\n Get a pointer to an array of direction vectors that can be used\n for quasirandom number generation.  The resulting pointer will\n reference an array of direction vectors in host memory.\n\n The array contains vectors for many dimensions.  Each dimension\n has 64 vectors.  Each individual vector is an unsigned long long.\n\n Legal values for \\p set are:\n - CURAND_DIRECTION_VECTORS_64_JOEKUO6 (20,000 dimensions)\n - CURAND_SCRAMBLED_DIRECTION_VECTORS_64_JOEKUO6 (20,000 dimensions)\n\n \\param vectors - Address of pointer in which to return direction vectors\n \\param set - Which set of direction vectors to use\n\n \\return\n - CURAND_STATUS_OUT_OF_RANGE if the choice of set is invalid \\n\n - CURAND_STATUS_SUCCESS if the pointer was set successfully \\n"]
pub unsafe fn curandGetDirectionVectors64<T: ::cuda_libs::types::CudaAsPtr>(
    mut vectors: T,
    set: curandDirectionVectorSet_t,
) -> Result<(), crate::sys::curandStatus_t> {
    let status = unsafe {
        crate::sys::curandGetDirectionVectors64(
            vectors.as_mut_ptr() as *mut *mut curandDirectionVectors64_t,
            set,
        )
    };
    if status == crate::sys::curandStatus_t::CURAND_STATUS_SUCCESS {
        Ok(())
    } else {
        Err(status)
    }
}
#[doc = " \\brief Get scramble constants for 64-bit scrambled Sobol' .\n\n Get a pointer to an array of scramble constants that can be used\n for quasirandom number generation.  The resulting pointer will\n reference an array of unsinged long longs in host memory.\n\n The array contains constants for many dimensions.  Each dimension\n has a single unsigned long long constant.\n\n \\param constants - Address of pointer in which to return scramble constants\n\n \\return\n - CURAND_STATUS_SUCCESS if the pointer was set successfully \\n"]
pub unsafe fn curandGetScrambleConstants64(
) -> Result<*mut ::std::os::raw::c_ulonglong, crate::sys::curandStatus_t> {
    let mut out_0: std::mem::MaybeUninit<*mut ::std::os::raw::c_ulonglong> =
        std::mem::MaybeUninit::uninit();
    let status = unsafe { crate::sys::curandGetScrambleConstants64(out_0.as_mut_ptr() as *mut _) };
    if status == crate::sys::curandStatus_t::CURAND_STATUS_SUCCESS {
        unsafe { Ok(out_0.assume_init()) }
    } else {
        Err(status)
    }
}
impl CurandGenerator {
    pub fn new(rng_type: crate::sys::curandRngType_t) -> Result<Self, crate::sys::curandStatus_t> {
        unsafe {
            let mut handle = std::ptr::null_mut();
            let status = crate::sys::curandCreateGenerator(&mut handle, rng_type);
            if status == crate::sys::curandStatus_t::CURAND_STATUS_SUCCESS {
                Ok(Self { handle })
            } else {
                Err(status)
            }
        }
    }
}
impl Drop for CurandGenerator {
    fn drop(&mut self) {
        unsafe {
            crate::sys::curandDestroyGenerator(self.handle);
        }
    }
}
