name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CUDA_HOME: /usr/local/cuda
      CUDNN_PATH: /usr/include/x86_64-linux-gnu/cudnn.h

    steps:
    - name: Install cuda keyring
      run: wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb && sudo dpkg -i cuda-keyring_1.1-1_all.deb
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cuda libcudnn-dev
    - uses: actions/checkout@v4
    - name: Run Autogen
      run: cargo run -p autogen --verbose
    - name: Build
      run: cargo build --verbose
    - name: Install nightly Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        targets: nvptx64-nvidia-cuda
        components: rust-src,rustfmt,clippy,rust-analyzer
    - name: Assemble cuda toolchain
      run: cargo run -p cuda_rustc --bin cuda_toolchain_build
    - name: Dereference toolchain symlinks
      run: tar -czhf cuda-toolchain.tar.gz -C target cuda-toolchain
    - name: Upload cuda toolchain artifact
      uses: actions/upload-artifact@v4
      with:
        name: cuda-toolchain
        path: cuda-toolchain.tar.gz